# Generated by Django 5.2.4 on 2025-07-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_profile_avatar_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nacimiento',
        ),
    ]
