# Generated by Django 5.2.4 on 2025-07-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_profile_bio_remove_profile_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cel',
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
