# Generated by Django 5.2.4 on 2025-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/default-avatar.png', upload_to='avatars/'),
        ),
    ]
