# Generated by Django 5.2.4 on 2025-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default-avatar.png', null=True, upload_to='static/img'),
        ),
    ]
