# Generated by Django 5.2.4 on 2025-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
