# Generated by Django 5.2.4 on 2025-07-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_remove_reserva_personas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='respuesta_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
