# Generated by Django 5.2.4 on 2025-07-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_remove_reserva_usuario_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(upload_to='about_photo/'),
        ),
    ]
